
# Generated by the protocol buffer compiler. DO NOT EDIT!
# source: secure_message.proto

import protobuf

class SecureMessage:
    # This would include methods and attributes for SecureMessage
    pass
